# Generated by Django 5.1.2 on 2024-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_genre_alter_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("Wishlist", "Wish List"),
                    ("Reading", "Reading"),
                    ("Completed", "Completed"),
                ],
                default="to_read",
                max_length=10,
            ),
        ),
    ]
